server:
  port: 8082
security:
  oauth2:
    client:
      clientId: demoClientId
      clientSecret: demoClientSecret
      accessTokenUri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/master/protocol/openid-connect/auth
    resource:
      userInfoUri: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
